name: CI

on:
  push:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: seanzhengw/sphinx-pages@master
        with:
          github_token: ${{ secrets.DEV_TOKEN }}
